### ISSUE TITLE
Project Direction

### ISSUE THREAD

**Issue by nhairs** [nhairs/python-json-logger#1]
Hi all,

Pending [the PEP 541 Request](https://github.com/pypi/support/issues/3607), I wanted to gather community feedback on the direction of this project.

My current thoughts are:

### Version 3.0.0

Goal: bring project into maintained state

- [x] Move to `pyproject.toml`
- [x] Ensure local development works (local linting, testing, building, etc)
- [x] Ensure CI works (test all versions, run on PRs etc)
- [x] Update supported python versions
  - [x] drop 3.6 support
  - [x] CPython 3.7-3.12 (ubuntu, win, mac)
  - [x] Pypy 3.7-3.10 (ubuntu, win, mac)
- Bug fixes
  - [x] https://github.com/madzak/python-json-logger/issues/185
    #2 
  - [x] https://github.com/madzak/python-json-logger/issues/173
    #4 

### Version 3.x

Goal: modernise package and include feature requests

- Existing feature requests from old repository
- [x] ORJSON (and other?) encoders
  #9 

### Support Policy

Security support: any python version that makes up at least 5% of total downloads and within 2 years of EOL (currently 3.7+)

Bug fixes and new features: only currently maintained versions of python (currently 3.8+)

### Maintainers

I'd like to look for 1-3 persons who are interested in helping maintain the project. These persons would also serve as a "backup" to prevent this repository from becoming unmaintained. If you'd like to be involved let me know

**Comment by juliangilbey** [comment]
Brilliant, thanks @nhairs!  One small suggestion: please could you import the tags from the original project as well?

**Comment by nhairs** [comment]
> Brilliant, thanks @nhairs! One small suggestion: please could you import the tags from the original project as well?

Good call @juliangilbey. All tags are now pushed (ranging from `v0.1.2` - `v2.0.7`)

**Comment by juliangilbey** [comment]
One other thing; the CHANGELOG.md file should either be kept up to date as you're making these changes or retired.

**Comment by nhairs** [comment]
> One other thing; the CHANGELOG.md file should either be kept up to date as you're making these changes or retired.

Another good pick-up - I didn't notice that that file was there :facepalm:. I've updated it and linked to it from the README.

**Comment by jdmoldenhauer** [comment]
@nhairs thank you so much for taking up the flag on this!

I looked at a few [PEP 541 requests](https://github.com/pypi/support/issues?q=is%3Aissue+is%3Aclosed+label%3A%22PEP+541%22+), and it seems like they tend to not get closed unless the previous owner does some work in pypi. Do you have any plans for If the previous owner remains unresponsive?

Thanks again for doing this work for the community.

**Comment by nhairs** [comment]
Thanks @jdmoldenhauer 

> I looked at a few [PEP 541 requests](https://github.com/pypi/support/issues?q=is%3Aissue+is%3Aclosed+label%3A%22PEP+541%22+), and it seems like they tend to not get closed unless the previous owner does some work in pypi. Do you have any plans for If the previous owner remains unresponsive?

I ended up talking very briefly about this on the PyPI discord. The TLDR is that they're aware that the current PyPI maintainers can't really look after the requests which is what is causing the large backlog; and that [they in the process of hiring a dedicated person to handle these requests](https://pythonsoftwarefoundation.applytojob.com/apply/nyYHuOha9h/PyPI-Support-Specialist) - applications close 1 May.

Although I expect it's probably going to be at least a few months before any action happens on the PEP 541 request I made, I'm working on the assumption that it will eventually happen. In the mean time I'm publishing built packages via [the project releases](https://github.com/nhairs/python-json-logger/releases) which can be used directly as a work around.

**Comment by nhairs** [comment]
I've put together a PR showcasing a potential `4.x` release. Any feedback would be appreciated :pray:

https://github.com/nhairs/python-json-logger/pull/9

**Comment by nhairs** [comment]
With:
- #9
- #11 
- #12 

I'm comfortable with where the project is going from a code point of view. If the PEP 541 request goes through I will look for maintainers then.

Before I close off this issue would there be any interest in an announcement mailing list for new versions etc? (similar to https://groups.google.com/g/dnspython-announce)

**Comment by cunla** [comment]
I am happy to join as a maintainer. I have experience maintaining python packages.

**Comment by hhoswaldo** [comment]
I am happy to help. Let me know if you need help.
