### ISSUE TITLE
Add the package to pypi

### ISSUE THREAD

**Issue by pikhovkin** [nhairs/python-json-logger#20]
Add the package to pypi

**Comment by nhairs** [comment]
Hi @pikhovkin,

The intention is to add this project to PyPI in some form or the other - either through a PEP 541 request for the original name or under a new name.

Currently I am waiting on the outcome of the [PEP 541 request](https://github.com/pypi/support/issues/3607).

In the mean time I am publishing releases to GitHub which you can [install from](https://nhairs.github.io/python-json-logger/latest/quickstart/#install-from-github). Or you can install from source (either using git URLs or locally).

**Comment by black-snow** [comment]
PEP 541 doesn't seem to move - I'd vote for a new package.

**Comment by monosans** [comment]
Thanks for maintaining python-json-logger! But I'm currently missing a way to auto-update the package via dependabot/renovate. Publishing the package on PyPI would be very helpful! 

+1 for the new package

**Comment by tva1992** [comment]
Any update on this?

**Comment by nhairs** [comment]
The PyPI support person has been working through the backlog of PEP 541 requests.

To give you an idea there are currently 371 open requests. On the GitHub website this equates to about 15 pages of requests. The support agent is working backwards (oldest first), and is on page 12. This project is on page 10. So we're getting close to being looked at.

I'll note that even once the process begins it will take at least 6 weeks as that's the grace period for the original owner to respond before the project is considered abandoned.

**Comment by pikhovkin** [comment]
@nhairs, but `py-json-logger`  is already available now, for example

**Comment by nhairs** [comment]
For those not following the other issue, the PEP541 process has started so we should have an outcome in ~6 weeks.

**Comment by nhairs** [comment]
We are now on PyPI :tada:
